let information = {
    1: {
        title: 'I Should Let You Go',
        image: 'https://i1.sndcdn.com/artworks-000357320508-clk3zd-t500x500.jpg',
        info: 'Track 1 from the \'This is all in my head\' EP',
        released: 'June 3, 2018',
        download: 'http://stereoload.com/a-himitsu/i-should-let-you-go-feat-nori',
        google_drive: 'https://drive.google.com/file/d/1y_kVQUfVAYQe0b3LD9l5OK_ZA3i5yvn_/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/i-should-let-you-go-feat-nori',
        spotify: 'https://open.spotify.com/track/4uZCpj7gq9JBGfetiYYiwa?si=kYQVfT86TMSRqovvY4Rl2g',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/i-should-let-you-go-feat-nori',
        youtube: 'https://www.youtube.com/watch?v=Xzq3z9tFkbk',
        itunes: 'https://itunes.apple.com/us/album/this-is-all-in-my-head-single/1394410727',
        buy: 'https://ahimitsu.bandcamp.com/track/i-should-let-you-go-feat-nori',
        lyrics: 'https://docs.google.com/document/d/1nRFxp-NaIcIFXbQG1AflzjeTyAPK8d5Xbbvx3LqRzZM/edit?usp=sharing',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/454502682&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    2: {
        title: 'Don\'t Cry',
        image: 'https://i1.sndcdn.com/artworks-000357320508-clk3zd-t500x500.jpg',
        info: 'Track 2 from the \'This is all in my head\' EP',
        released: 'June 3, 2018',
        download: 'http://stereoload.com/a-himitsu/dont-cry-feat-nori',
        google_drive: 'https://drive.google.com/file/d/1Sgtdxe8EoUAdvW0oiUCaDCzgMGZ0OF26/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/dont-cry-feat-nori',
        spotify: 'https://open.spotify.com/track/0Ux1bvPcx6vzH5IYLUoS1j?si=zsTjVjpNRmmCgtH-kevKaA',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/dont-cry-feat-nori',
        youtube: 'https://www.youtube.com/watch?v=KCwA65MuVko',
        itunes: 'https://itunes.apple.com/us/album/this-is-all-in-my-head-single/1394410727',
        buy: 'https://ahimitsu.bandcamp.com/track/dont-cry-feat-nori',
        lyrics: 'https://docs.google.com/document/d/1QfNLeMEaqi8pNP64MH4a3_2CY4gU4XzF-lcpp7DEQ3Q/edit?usp=sharing',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/454504344&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    3: {
        title: 'Fragile',
        image: 'https://i1.sndcdn.com/artworks-000357320508-clk3zd-t500x500.jpg',
        info: 'Track 3 from the \'This is all in my head\' EP',
        released: 'June 3, 2018',
        download: 'http://stereoload.com/a-himitsu/fragile',
        google_drive: 'https://drive.google.com/file/d/1cKGiKsjh3EtWaj6Xi9zCjaQk6_w0jTox/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/fragile',
        spotify: 'https://open.spotify.com/track/4S8xGQ0CQeW3ZPlJOxX8r8?si=SNq84Oi4Q3iEI_MnEjWGaw',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/fragile',
        youtube: 'https://www.youtube.com/watch?v=CHJJRdrFw5s',
        itunes: 'https://itunes.apple.com/us/album/this-is-all-in-my-head-single/1394410727',
        buy: 'https://ahimitsu.bandcamp.com/track/fragile',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/454504929&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    4: {
        title: 'Two Places',
        image: 'https://i1.sndcdn.com/artworks-000242466576-6kqr68-t500x500.jpg',
        info: '',
        released: 'September 11, 2017',
        download: 'http://stereoload.com/a-himitsu/two-places',
        google_drive: 'https://drive.google.com/file/d/0B9WcVQFtPSIrbks5SGZxTFlLMTQ/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/two-places',
        spotify: 'https://open.spotify.com/track/3jSWaKfBYnKOlS9gYChXdO?si=L8IVVUDxSAK4NbvXWWimdg',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/two-places',
        youtube: 'https://www.youtube.com/watch?v=lK6QXbYKzhA',
        itunes: 'https://itunes.apple.com/us/album/two-places-single/id1282092743',
        buy: 'https://ahimitsu.bandcamp.com/track/two-places',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/342184645&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    5: {
        title: 'Cosmic Storm',
        image: 'https://i1.sndcdn.com/artworks-000225872918-zioeu2-t500x500.jpg',
        info: 'A rework of a short track that I made back in 2015.',
        released: 'June 1, 2017',
        download: 'http://stereoload.com/a-himitsu/cosmic-storm',
        google_drive: 'https://drive.google.com/file/d/1IarQFJ9A9OXCDEULmwZ4whiO_He5Wl41/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/cosmic-storm',
        spotify: 'https://open.spotify.com/track/3rjD3b42l3mErsNR74Xn5J?si=e82mQsxjQ9GkQwkFBVV6zQ',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/cosmic-storm',
        youtube: 'https://www.youtube.com/watch?v=C8fkSFIf3hY',
        itunes: 'https://itunes.apple.com/us/album/cosmic-storm-single/id1243836626',
        buy: 'https://ahimitsu.bandcamp.com/track/cosmic-storm',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/325882774&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    6: {
        title: 'Realms',
        image: 'https://i1.sndcdn.com/artworks-000208524001-tftdgi-t500x500.jpg',
        info: 'Collaboration with Hinkik.',
        released: 'February 19, 2017',
        download: 'https://www.toneden.io/hinkik/post/hinkik-a-himitsu-realms',
        google_drive: 'https://www.toneden.io/hinkik/post/hinkik-a-himitsu-realms',
        soundcloud: 'https://soundcloud.com/a-himitsu/hinkik-a-himitsu-realms',
        spotify: 'https://open.spotify.com/track/5JBGN8R0mRAzmvDKFNkVmY?si=jpph9hqAQGiEjDj_-1_IPw',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/realms',
        youtube: 'https://www.youtube.com/watch?v=Nv5YxKqQ65A',
        itunes: 'https://itunes.apple.com/us/album/realms-single/1207587842',
        buy: 'https://ahimitsu.bandcamp.com/track/realms',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/308484458&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    7: {
        title: 'In Love',
        image: 'https://i1.sndcdn.com/artworks-000190303387-zya2ng-t500x500.jpg',
        info: 'Featuring Nori on vocals',
        released: 'October 16, 2016',
        download: 'http://stereoload.com/a-himitsu/in-love-feat-nori',
        google_drive: 'https://drive.google.com/file/d/0B9WcVQFtPSIrWDdZMmZEVUV5a0U/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/in-love-feat-nori',
        spotify: 'https://open.spotify.com/track/57fwa4k6jPTYF3ziZPvAZO?si=ZFpd25_ZS3OD_HrtGoONuw',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/in-love-feat-nori',
        youtube: 'https://www.youtube.com/watch?v=rXb7Dkut4BE',
        itunes: 'https://itunes.apple.com/us/album/in-love-feat.-nori-single/id1166298332',
        buy: 'https://ahimitsu.bandcamp.com/track/in-love-feat-nori',
        lyrics: 'https://docs.google.com/document/d/1ODj_ejiFLoYwhNLfInWERLOP5yWeSC55NeZKXqfuzhA/edit?usp=sharing',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/289581187&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    8: {
        title: 'Astray',
        image: 'https://i1.sndcdn.com/artworks-000179354503-20rb5l-t500x500.jpg',
        info: 'Featuring Madi Larson on vocals',
        released: 'August 27, 2016',
        download: 'http://stereoload.com/a-himitsu/astray-feat-madi-larson',
        google_drive: 'https://drive.google.com/file/d/1V5nnIzyqR_JO3SX8dHbHUSvAdJbJad1d/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/astray-feat-madi-larson',
        spotify: 'https://open.spotify.com/track/6XeymCHkfV18GZ5Jph2iQ2?si=pmSWY6UnRSyziJaf7ApeeQ',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/astray-feat-madi-larson',
        youtube: 'https://www.youtube.com/watch?v=EBOzlJdlbyU',
        itunes: 'https://itunes.apple.com/us/album/astray-feat.-madi-larson-single/id1148337018',
        buy: 'https://ahimitsu.bandcamp.com/track/astray-feat-madi-larson',
        lyrics: 'https://docs.google.com/document/d/1LqvFcVcZ07JrUCOsnPf_gEGFcgKfoavB4eq8o9clRJo/edit?usp=sharing',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/280458454&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    9: {
        title: 'Reminisce',
        image: 'https://i1.sndcdn.com/artworks-000169723344-w42bf6-t500x500.jpg',
        info: 'Track 1 from the \'Reminisce\' EP',
        released: 'June 28, 2016',
        download: 'http://stereoload.com/a-himitsu/reminisce',
        google_drive: 'https://drive.google.com/file/d/0B9WcVQFtPSIrbU9RM3RCYm42Zlk/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/reminisce',
        spotify: 'https://open.spotify.com/track/0WDeEKsrhk61LLLO5HlwoQ?si=l9N5IjP-RIuY8zsBvve6PA',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/reminisce',
        youtube: 'https://www.youtube.com/watch?v=FbhzEWOuQbA',
        itunes: 'https://itunes.apple.com/us/album/reminisce-single/id1128913329',
        buy: 'https://ahimitsu.bandcamp.com/track/reminisce',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/271721656&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    10: {
        title: 'Jorg',
        image: 'https://i1.sndcdn.com/artworks-000169723344-w42bf6-t500x500.jpg',
        info: 'Track 2 from the \'Reminisce\' EP',
        released: 'June 28, 2016',
        download: 'http://stereoload.com/a-himitsu/jorg',
        google_drive: 'https://drive.google.com/file/d/0B9WcVQFtPSIrUjUwWHQyMDQtQWs/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/jorg',
        spotify: 'https://open.spotify.com/track/3P7BUobc7ZBtkacNufotzq?si=ha5dBbn-Tau5ZAoQY4IW5w',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/jorg',
        youtube: 'https://www.youtube.com/watch?v=U7oEZRwmm6E',
        itunes: 'https://itunes.apple.com/us/album/reminisce-single/id1128913329',
        buy: 'https://ahimitsu.bandcamp.com/track/jorg',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/271720602&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    11: {
        title: 'Waiting Just on You',
        image: 'https://i1.sndcdn.com/artworks-000156791208-kyjnvu-t500x500.jpg',
        info: 'Featuring Nori on vocals',
        released: 'March 27, 2016',
        download: 'http://stereoload.com/a-himitsu/waiting-just-on-you-feat-nori',
        google_drive: 'https://drive.google.com/file/d/17xBCTupikUQvadWjrUWjukQ-oTbpW4da/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/waiting-just-on-you-feat-nori',
        spotify: 'https://open.spotify.com/track/5ebfcgKaU2x6KnevyHKQay?si=oFeHZF1bR6mJz2Lm_i4pag',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/waiting-just-on-you-feat-nori',
        youtube: 'https://www.youtube.com/watch?v=QfDXiG9Q1GQ',
        itunes: 'https://itunes.apple.com/us/album/waiting-just-on-you-feat./id1097425378',
        buy: 'https://ahimitsu.bandcamp.com/track/waiting-just-on-you-feat-nori',
        lyrics: 'https://docs.google.com/document/d/13ZtrVfRVP-vQVZLLMy4sqo2w4aDphp7zh97guCzkIig/edit?usp=sharing',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/257603086&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    12: {
        title: 'Stories',
        image: 'https://i1.sndcdn.com/artworks-000138976572-egdnxq-t500x500.jpg',
        info: 'Using vocaloids for the vocal parts',
        released: 'December 6, 2015',
        download: 'http://stereoload.com/a-himitsu/stories',
        google_drive: 'https://drive.google.com/file/d/17xBCTupikUQvadWjrUWjukQ-oTbpW4da/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/stories-1',
        spotify: 'https://open.spotify.com/track/31V15HTPjkreSuZsHbNATu?si=D8BUqUQrSqWD7xtIqSotmg',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/stories',
        youtube: 'https://www.youtube.com/watch?v=xqTG3wDLtUY',
        itunes: 'https://itunes.apple.com/us/album/stories-single/id1065724001',
        buy: 'https://ahimitsu.bandcamp.com/track/stories',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/236802055&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    13: {
        title: 'Flourish, Wither, Bye',
        image: 'https://i1.sndcdn.com/artworks-000132366065-vd8yjf-t500x500.jpg',
        info: '',
        released: 'October 20, 2015',
        download: 'http://stereoload.com/a-himitsu/flourish-wither-bye',
        google_drive: 'https://drive.google.com/file/d/17xBCTupikUQvadWjrUWjukQ-oTbpW4da/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/flourish-wither-bye',
        spotify: 'https://open.spotify.com/track/6SGPd49XaEDnKABz70RGua?si=eB0JzG6qSQKv3_n9sup_Sw',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/flourish-wither-bye',
        youtube: 'https://www.youtube.com/watch?v=_2-BCUCTfhc',
        itunes: 'https://itunes.apple.com/us/album/flourish-wither-bye-single/id1051192484',
        buy: 'https://ahimitsu.bandcamp.com/track/flourish-wither-bye',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/227907037&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    14: {
        title: 'She closed her eyes in despair',
        image: 'https://i1.sndcdn.com/artworks-000169723344-w42bf6-t500x500.jpg',
        info: 'Track 3 from the \'Reminisce\' EP',
        released: 'September 14, 2015',
        download: 'http://stereoload.com/a-himitsu/she-closed-her-eyes-in-despair',
        google_drive: 'https://drive.google.com/file/d/0B9WcVQFtPSIrN1dHaGVRdXBKQXM/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/hon-blundade-i-ren-fortvivlan',
        spotify: 'https://open.spotify.com/track/0d7648LAP7tc4wR4IN7bzQ?si=moduJMC4Rfawo4fd_rdVFA',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/she-closed-her-eyes-in-despair',
        youtube: 'https://www.youtube.com/watch?v=8z6ES0M8bN0',
        itunes: 'https://itunes.apple.com/us/album/reminisce-single/id1128913329',
        buy: 'https://ahimitsu.bandcamp.com/track/she-closed-her-eyes-in-despair',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/223831826&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    15: {
        title: 'Easier to Fade',
        image: 'https://i1.sndcdn.com/artworks-000128987657-cl095d-t500x500.jpg',
        info: 'Featuring Madi Larson on vocals',
        released: 'September 4, 2015',
        download: 'http://stereoload.com/a-himitsu/easier-to-fade-feat-madi-larson',
        google_drive: 'https://drive.google.com/file/d/10cIJgjO1E4Br7Cy7aUjhNX9ZZc0a1KOF/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/easier-to-fade-feat-madi-larson',
        spotify: 'https://open.spotify.com/track/3mSiIlECYK31Bpyjo2vehV?si=UcdbtjuzRfOkZWKuHpt2Ug',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/easier-to-fade-feat-madi-larson',
        youtube: 'https://www.youtube.com/watch?v=zC-t6NehXSA',
        itunes: 'https://itunes.apple.com/us/album/easier-to-fade-feat.-madi/id1037568806',
        buy: 'https://ahimitsu.bandcamp.com/track/easier-to-fade-feat-madi-larson',
        lyrics: 'https://docs.google.com/document/d/13vfdbGVbfW-SjjfHXsbwsBiOxvkoZ_KnsRsPR40sYxI/edit?usp=sharing',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/223062346&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    16: {
        title: 'Adventures',
        image: 'https://i1.sndcdn.com/artworks-000120144966-9k2xww-t500x500.jpg',
        info: 'Released through Argofox',
        released: 'June 8, 2015',
        download: 'http://stereoload.com/a-himitsu/adventures-available-on-spotify',
        google_drive: 'https://soundcloud.com/argofox/a-himitsu-adventures',
        soundcloud: 'https://soundcloud.com/a-himitsu/adventures',
        spotify: 'https://open.spotify.com/track/19uuiVuN6YvFvetpjzfUYg?si=7J0mndOMQK-KFTGwpD3z3A',
        bandcamp: null,
        youtube: 'https://www.youtube.com/watch?v=ruE25BCgcYk',
        itunes: 'https://itunes.apple.com/us/album/adventures-single/997747952',
        buy: 'https://itunes.apple.com/us/album/adventures-single/997747952',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/209871375&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    17: {
        title: 'Cease',
        image: 'https://i1.sndcdn.com/artworks-000118475173-215a0t-t500x500.jpg',
        info: '',
        released: 'April 19, 2015',
        download: 'http://stereoload.com/a-himitsu/cease',
        google_drive: 'https://drive.google.com/file/d/1kZ_7CE-SykIyX1DyIxuAh4yyvI7AOrla/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/cease',
        spotify: 'https://open.spotify.com/track/6YJ96RgDJHo8TTpdTEzTv8?si=-Hdypy2HRKyGbMOIPdYnmg',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/cease',
        youtube: 'https://www.youtube.com/watch?v=MBzzGKsmnSw',
        itunes: 'https://itunes.apple.com/us/album/a-himitsu-ep/id999863849',
        buy: 'https://ahimitsu.bandcamp.com/track/cease',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/201541435&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    18: {
        title: 'Lost Within',
        image: 'https://i1.sndcdn.com/artworks-000118475173-215a0t-t500x500.jpg',
        info: 'Hatsune Miku for the vocals',
        released: 'December 30, 2014',
        download: 'http://stereoload.com/a-himitsu/lost-within',
        google_drive: 'https://drive.google.com/file/d/1_dTchjynuoTBp1EnyTOho8bPOkEh-MFM/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/lost-within',
        spotify: 'https://open.spotify.com/track/3Anjm2cjCMBfdGNLwAE74M?si=5J89P16IQfy9G73XjRWk-w',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/lost-within',
        youtube: 'https://www.youtube.com/watch?v=6WQjgHuUDWU',
        itunes: 'https://itunes.apple.com/us/album/a-himitsu-ep/id999863849',
        buy: 'https://ahimitsu.bandcamp.com/track/lost-within',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/183615430&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    19: {
        title: 'Icy Vindur',
        image: 'https://i1.sndcdn.com/artworks-000118475173-215a0t-t500x500.jpg',
        info: '',
        released: 'November 2, 2014',
        download: 'http://stereoload.com/a-himitsu/icy-vindur',
        google_drive: 'https://drive.google.com/file/d/1nRYPtuTQeJRiW_UB5JM3-q6iZa-5wS0Q/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/icy-vindur',
        spotify: 'https://open.spotify.com/track/0lgKwiOlIayT2G8hx7SjRE?si=owFMGFCYTpC1e4J1QBg5Tg',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/icy-vindur',
        youtube: 'https://www.youtube.com/watch?v=w2Y2P4ksQK8',
        itunes: 'https://itunes.apple.com/us/album/a-himitsu-ep/id999863849',
        buy: 'https://ahimitsu.bandcamp.com/track/icy-vindur',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/174998995&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    20: {
        title: 'Isolated Mind',
        image: 'https://i1.sndcdn.com/artworks-000118475173-215a0t-t500x500.jpg',
        info: '',
        released: 'October 10, 2014',
        download: 'http://stereoload.com/a-himitsu/isolated-mind',
        google_drive: 'https://drive.google.com/file/d/1xsKYmOI-FuzJDhJvfcaUm1laDGkQRtCu/view?usp=sharing',
        soundcloud: 'https://soundcloud.com/a-himitsu/isolated-mind',
        spotify: 'https://open.spotify.com/track/2dnTsOVPNWPapxwYY8fvQs?si=3fLkcPH5QsG7-EqUisfz8A',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/isolated-mind',
        youtube: 'https://www.youtube.com/watch?v=r7109mnvIu8',
        itunes: 'https://itunes.apple.com/us/album/a-himitsu-ep/id999863849',
        buy: 'https://ahimitsu.bandcamp.com/track/isolated-mind',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/171369630&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    21: {
        title: 'Lucid Dream',
        image: 'https://i1.sndcdn.com/artworks-000136889530-g2j7my-t500x500.jpg',
        info: '',
        released: 'May 10, 2015',
        download: 'https://ahimitsu.bandcamp.com/track/lucid-dream',
        google_drive: 'https://ahimitsu.bandcamp.com/track/lucid-dream',
        soundcloud: 'https://soundcloud.com/skyfallaudio/a-himitsu-lucid-dream',
        spotify: 'https://open.spotify.com/track/74tEOiX7TW7llKcp9ohQdL?si=IG9D0nluTqK9CWeLrO3cLg',
        bandcamp: 'https://ahimitsu.bandcamp.com/track/lucid-dream',
        youtube: 'https://www.youtube.com/watch?v=Mf7rdM9ho7M',
        itunes: 'https://itunes.apple.com/us/album/lucid-dream-single/id999823269',
        buy: 'https://ahimitsu.bandcamp.com/track/lucid-dream',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/196156603&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    },
    22: {
        title: 'Where Silence is Nonexistent',
        image: 'https://i1.sndcdn.com/artworks-000128631809-44n7y2-t500x500.jpg',
        info: '',
        released: 'September 15, 2014',
        download: 'https://ahimitsu.bandcamp.com/track/where-silence-is-nonexistent',
        google_drive: 'https://ahimitsu.bandcamp.com/track/where-silence-is-nonexistent',
        soundcloud: 'https://soundcloud.com/a-himitsu/where-silence-is-nonexistent',
        spotify: null,
        bandcamp: 'https://ahimitsu.bandcamp.com/track/where-silence-is-nonexistent',
        youtube: 'https://www.youtube.com/watch?v=m7eM8BXG3eg',
        itunes: null,
        buy: 'https://ahimitsu.bandcamp.com/track/where-silence-is-nonexistent',
        sc_embed: 'https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/tracks/167823205&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true&visual=true'
    }
}

export {information}